main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-blog', new_blog, name="new-blog"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('post', new_post, name="post"),
    path('create2', create2, name="create2"),
    path('post/<int:id>', detail2, name="detail2"),
    path('edit2/<int:id>', edit2, name="edit2"),
    path('update2/<int:id>', update2, name="update2"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
    path('likes/<int:post_id>', likes, name="likes"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>/', mypage, name='mypage'),
    path('follow/<int:id>/', follow, name='follow'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from main.models import Post, Blog

# Create your views here.
def mypage(request,id):
    print(f"Received ID: {id}, Type: {type(id)}")
    user = get_object_or_404(User, pk=id)
    posts = Post.objects.filter(writer=user)
    context = {
        'user': user,
        'posts': posts,
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    follow_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in follow_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(follow_user.profile)
    else:
        user.profile.followings.add(follow_user.profile)
    return redirect('users:mypage', follow_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>마이페이지에 오신 것을 환영합니다</h1>
User : {{ user }} <br>
UserProfile : {{ user.profile }} <br>

<p>팔로워수: {{ user.profile.followers.count }}</p>
<p>팔로잉수: {{ user.profile.followings.count }}</p>

{% if request.user != user %}
    {% if request.user.profile in user.profile.followers.all %}
        <a href="{% url 'users:follow' user.id %}">
            <button type="button" class="btn btn-outline-info">언팔로우</button>
        </a>
    {% else %}
        <a href="{% url 'users:follow' user.id %}">
            <button type="button" class="btn btn-info">팔로우</button>
        </a>
    {% endif %}
{% endif %}



<h3>나이가 ...{{user.profile.age}}살..? 흠.</h3>
<h3>MBTI가 {{user.profile.mbti}}시네여</h3>
<h3>내 포스트</h3>
<ul>
    {% for post in posts %}
        <li>
            <a href="{% url 'main:detail2' post.id %}">{{post.title}}</a>
            <p>작성자 : {{post.writer}}</p>
            <p>날짜 : {{post.pub_date}}</p>
        </li>
    {% endfor %}

{% endblock %}