main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-blog', new_blog, name="new-blog"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('post', new_post, name="post"),
    path('create2', create2, name="create2"),
    path('post/<int:id>', detail2, name="detail2"),
    path('edit2/<int:id>', edit2, name="edit2"),
    path('update2/<int:id>', update2, name="update2"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
    path('likes/<int:post_id>', likes, name="likes"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>/', mypage, name='mypage'),
    path('follow/<int:id>/', follow, name='follow'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name=models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=50)
    writer = models.CharField(max_length=30)
    content = models.TextField()
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to='blog/', blank=True, null=True)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:20]

class Post(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to='post/', blank=True, null=True)
    views = models.PositiveIntegerField(default=0, help_text="조회수")
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    like=models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:20]
class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)
    
    def str (self):
        return self.post.title + " : " + self.content[:20] + "by" + self.writer.profile.nickname

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.models import User

from .models import *
# Create your views here.

def mainpage(request):
    context = {
        'generation': 13,
        'info': {'weather': '좋음', 'feeling': '배고픔(?)', 'note': '아기사자 화이팅!'},
        'shortKeys': [
            '들여쓰기: Tab',
            '내어쓰기: Shift + Tab',
            '주석 처리: 윈도우 - Ctrl + /, 맥 - command + /',
            '자동 정렬: Shift + Alt + F or Ctrl + K + F',
            '한 줄 이동: Alt + 방향키(위/아래)',
            '한 줄 삭제: Ctrl + Shift + k or Ctrl + x',
            '같은 단어 전체 선택: Ctrl + Shift + L'
        ]
    }
    return render(request, 'main/mainpage.html', context)

def secondpage(request):
    blogs = Blog.objects.all()
    posts = Post.objects.all()
    context = {
        'blogs': blogs,
        'posts': posts,
    }
    return render(request, 'main/secondpage.html', context)


def new_blog(request):
    blogs = Blog.objects.all()
    return render(request, 'main/new-blog.html')

def detail(request, id):
    blog = get_object_or_404(Blog, pk=id)
    try:
        blog_writer = User.objects.get(username=blog.writer)
    except User.DoesNotExist:
        blog_writer = None
    return render(request, 'main/detail.html', {'blog': blog, 'blog_writer': blog_writer},)

def create(request):
    new_blog = Blog()

    new_blog.title = request.POST['title']
    new_blog.writer = request.POST['writer']
    new_blog.content = request.POST['content']
    new_blog.pub_date = timezone.now()
    new_blog.image = request.FILES.get('image')

    new_blog.save()

    return redirect('main:detail', new_blog.id)

def edit(request, id):
    edit_blog = Blog.objects.get(pk=id)
    return render(request, 'main/edit.html', {'blog': edit_blog})

def update(request, id):
    update_blog = Blog.objects.get(pk=id)
    update_blog.title = request.POST['title']
    update_blog.writer = request.POST['writer']
    update_blog.content = request.POST['content']
    update_blog.pub_date = timezone.now()


    update_blog.save()
    return redirect('main:detail', update_blog.id)

def create2(request):
    if request.user.is_authenticated:
        new_post = Post()

        new_post.title = request.POST['title']
        new_post.writer = request.user
        new_post.content = request.POST['content']
        new_post.pub_date = timezone.now()
        new_post.image = request.FILES.get('image')

        new_post.save()

        words = new_post.content.split()
        tag_list = []

        for w in words:
            if len(w) > 0 and w[0] == '#':
                tag_list.append(w[1:])
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)
        return redirect('main:detail2', new_post.id)
    else:
        return redirect('account:login')

def new_post(request):
    return render(request, 'main/post.html')

def detail2(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == 'GET':
        comments = Comment.objects.filter(post=post)
        return render(request, 'main/detail2.html', {'post': post, 'comments': comments})
    elif request.method == 'POST':
        new_comment = Comment()
        new_comment.post = post
        new_comment.writer = request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now()
        new_comment.save()
        return redirect('main:detail2', id)
    post.views += 1
    post.save(update_fields=['views'])
    return render(request, 'main/detail2.html', {'post': post})

def edit2(request, id):
    edit_post = Post.objects.get(pk=id)
    return render(request, 'main/edit2.html', {'post': edit_post})

def update2(request, id):
    update_post = Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user == update_post.writer:
        update_post.title = request.POST['title']
        update_post.content = request.POST['content']
        update_post.pub_date = timezone.now()
        update_post.views = request.POST.get('views', update_post.views)
        if request.FILES.get('image'):
            update_post.image = request.FILES.get('image')
        
        update_post.tags.clear() 

        words = update_post.content.split()
        tag_list = []

        for w in words:
            if len(w) > 0 and w[0] == '#':
                tag_list.append(w[1:])

        for t in tag_list:
            tag, _ = Tag.objects.get_or_create(name=t)
            update_post.tags.add(tag.id)

        update_post.save()
        Tag.objects.filter(posts=None).delete()
        return redirect('main:detail2', update_post.id)
    return redirect('accounts:login', update_post.id)

def delete(request, id):
    delete_post= Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:secondpage')

def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'main/tag-list.html',{'tags': tags})
def tag_posts(request, tag_id):
    tag=get_object_or_404(Tag, id=tag_id)
    posts = tag.posts.all()
    return render(request, 'main/tag-post.html',{'tag': tag,'posts': posts})

def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -= 1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    return redirect('main:detail2', post.id)

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3>{{blog.title}}</h3>
    <a href="{% url 'users:mypage' blog_writer.id %}">작성자 : {{blog_writer.username}}</a>
    날짜 : {{blog.pub_date}}
    <hr />
    {% if blog.image %}
        <p><img src="{{ blog.image.url }}" alt="사진" width="100px"></p>
    {% endif %}

    <p>{{blog.content}}</p>
    <a href="{% url 'main:edit' blog.id %}">글 수정하기</a> 
    <br>
{% endblock %}

main/templates/main/detail2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3>{{post.title}}</h3>
        <a href="{% url 'users:mypage' post.writer.id %}">작성자 : {{post.writer.username}}</a>
        날짜 : {{post.pub_date}}
        조회수: {{ post.views }}
        <a href="{% url 'main:likes' post.id %}">
            {% if user in post.like.all %} 취소 {% else %} 좋아요 {% endif %}
        </a>
        {{ post.like_count }}개        
        <p>
            {% for tag in post.tags.all %}
                <a href="{% url 'main:tag-posts' tag.id %}">#{{ tag.name }}</a>
            {% endfor %}
        </p>
        <hr />
        {% if blog.image %}
            <p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
        {% endif %}
        <p>{{post.content}}</p>
        {% if post.writer == user %}
        <a href="{% url 'main:edit2' post.id %}">글 수정하기</a>
        <a href="{% url 'main:delete' post.id %}">삭제하기</a>
        {% endif %}
    <br>
    <div class="comment_container">
        <div class="comment_form">
            <h2></h2>
            <form action="{% url 'main:detail2' post.id %}"method="POST">
                {% csrf_token %}
                댓글 쓰기 : <input type="text" name="content">
                <input type="submit" name="submit">
            </form>
        </div>
        <div class="comment_list">
            {% for comment in comments %}
            <hr>
            <h4>작성자 : <a href="{% url 'users:mypage' comment.writer.id %}">{{comment.writer.username}}</a></h4>
            <p>내용 : {{comment.content}}</p>
            <p>{{comment.pub_date}}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %} 
<h2>수정중...</h2>
<form action="{% url 'main:update' blog.id %}" method="POST" enctype="multipart/form-data">
{% csrf_token %} 
<p>제목: <input type="text" name="title" value="{{blog.title}}"></p>
<p>작성자: <input type="text" name="writer" value="{{blog.writer}}"></p>
{% if blog.image %}
<p><img src="{{ blog.image.url }}" alt="사진" width="100px"></p>
{% endif %}
<p>사진: <input type="file" name="image"></p>
<p>내용: <textarea type="text" name="content" id=
"" cols="30" rows="10">{{blog.content}}</textarea></p>
<button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/edit2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중...</h2>
<form action="{% url 'main:update2' post.id %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<p>제목: <input type="text" name="title" value="{{post.title}}"></p>
<p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
{% if blog.image %}
<p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
{% endif %}
<p>사진: <input type="file" name="image"></p>
<p>내용: <textarea type="text" name="content" id="" cols="30" rows="10">{{post.content}}</textarea></p>
<button type="submit">제출</button>
</form>
{% endblock %} 

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <img src="{% static 'images/image.png' %}" alt="image" width="100px">
    <h1 class="contents">2025 멋쟁이사자처럼 {{generation}}기</h1>
    <div class="contents">Welcome Django!</div>
    <div>🦁 머쩅이 사자의 일기짱🦁 </div>
    <ul>
        <li>오늘의 날씨 : {{info.weather}}</li>
        <li>오늘의 기분 : {{info.feeling}}</li>
        <li>{{info.note}}</li>
    </ul>
    <div>🦁 VS Code 단축키🦁 </div>
    <ul>
        {% for s in shortKeys %}
        <li>{{s}}</li>
        {% endfor %}
    </ul>

{% endblock %}

main/templates/main/new-blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목 : <input type="text" name="title"></p>
    <p>작성자 : <input type="text" name="writer"></p>
    <p>사진: <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create2' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목 : <input type="text" name="title"></p>
    <!-- <p>작성자 : <input type="text" name="writer"></p> -->
    <p>조회수: <input type="text" name="views"></p>
    <p>사진: <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/secondpage.html
{% extends 'base.html' %}
{% block content %}

    <h1 class="contents">2025 멋쟁이사자처럼 13기</h1>
    <div class="contents">This is Second Page</div>
    <div>
        <div>
            {% for blog in blogs %} 
            <div>
            <hr/>
            <h3>{{blog.title}}</h3>
            {{blog.writer}} | {{blog.pub_date}}<br>
            {{blog.content}} 
            {{blog.summary}}
            <a href="{% url 'main:detail' blog.id %}">자세히 보기</a>
            <br>
            </div>
            {% endfor %}
            </div>
            <div>
                {% if user.is_authenticated %}
                <a href="{% url 'main:post' %}">글쓰기</a>
                {% endif %}
            </div>
            {% for post in posts %}
            <div>
                <hr/>
                <h3>{{post.title}}</h3>
                {{post.writer}} | {{post.pub_date}} | {{post.views}}<br>
                {{post.summary}}
                <a href="{% url 'main:detail2' post.id %}">자세히 보기</a>
                <br>
            {% endfor %}
            </div>
                

    </div>
{% endblock %}

main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<div> 
    <h1>해시태그 목록</h1>
    <hr>
    {% for t in tags %}
    <div>
        <h2><a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>#{{tag}}가 달린 게시글</h1>
    <hr>
    <div>
        {% for p in posts %}
        <hr />
        <h3>{{p.title}}</h3>
        {{p.writer}} | {{p.pub_date}}<br>
        {{p.summary}}
        <a href="{% url 'main:detail2' p.id %}">자세히 보기</a>
        <br>
        {% endfor %}
    </div>
</div>
{% endblock %}